src/components/PromptList.tsx, src/hooks/useBreadcrumb.ts, src/lib/utils.ts
Refine a bit more the parsing of the query, to support code snippets and properly format title and detail
Related-to: #398
=> fix: properly parse title and prompt when there are snippets

src/components/Chat.tsx, src/components/PromptList.tsx, src/hooks/useAlertsStore.ts, src/hooks/useBreadcrumb.ts, src/hooks/usePromptsStore.ts, src/lib/utils.ts, src/types.ts
Filtering out prompts, and alerts that includes empty answer and questions.
Fix answer trim, If `Query:` was not found return the `answer`.
=> fix: filtering out empty answer prompts, alerts

.github/workflows/_security-checks.yml, .github/workflows/_static-checks.yml, .github/workflows/_unit-tests.yml, package-lock.json, package.json, src/hooks/__tests__/useBrowserNotification.test.ts, src/hooks/useBrowserNotification.ts, vitest.config.ts
=> chore: add coveralls coverage report

src/components/Markdown.tsx
Sometimes Continue and Copilot return malformed markdown for code highlight, we can skip those malformed markdown avoiding ReactMarkdown issue
=> fix: skip malformed markdown

src/components/Dashboard.tsx
=> fix: formatting alert time in the table, add seconds

src/viz/LineChart.tsx
=> fix: alerts line chart sorting

src/components/Error.tsx, src/components/ErrorBoundary.tsx, src/components/Header.tsx, src/components/__tests__/ErrorBoundary.test.tsx, src/main.tsx
wrap the app with a generic error boundary
=> feat: add ErrorBoundary

src/components/Chat.tsx, src/components/Dashboard.tsx, src/components/Help.tsx, src/components/Markdown.tsx
this includes some fixes for the markdown implementation across the project
visually there isn't much difference, there are minimal adjustments. But now the <Markdown /> component automatically takes care of proper rendering, thus fixing the broken markdown in the chats:
https://github.com/user-attachments/assets/0b2f0adf-6deb-450d-91cf-61b87e580cc7
=> fix: fix basic markdown usage

src/components/Dashboard.tsx, src/components/Markdown.tsx, src/components/__tests__/Dashboard.test.tsx
**BEFORE**
**AFTER**
**Fix trigger token spacing**
=> fix(alerts-table): trigger token box and copy to clipboard icon

src/components/Dashboard.tsx
We are missing the clear button in the input search
=> fix(alerts-table): add clear button to input search

src/components/Header.tsx, src/components/__tests__/ErrorBoundary.test.tsx, src/lib/test-utils.tsx, src/main.tsx
=> feat: add dark mode switcher

src/App.tsx, src/hooks/__tests__/useSee.test.ts, src/hooks/useSse.ts
implementes @alex-mcgovern suggestiong to rely on react-query to refetch the data. Works great, I tested it locally!
=> refactor: use react-query to implement refetch logic

src/components/Dashboard.tsx, src/hooks/useAlertSearch.ts, src/hooks/useAlertsData.ts, src/hooks/useAlertsStore.ts, src/types.ts
no visual change. just refactors the data fetching for alerts so that it is using react-query. Zustand is still used to handle the search state, no major refactor there
=> refactor: use react-query for fetching alerts

package.json, src/components/ui/chat/chat-bubble.tsx, src/components/ui/sheet.tsx, src/components/ui/sidebar.tsx
This just removes the `class-variance-authority` dependency from the project, as it is equivalent to `tailwind-variants`, which is already used in `@stacklok/ui-kit`.
=> chore: remove CVA

src/api/generated/@tanstack/react-query.gen.ts, src/api/generated/sdk.gen.ts, src/api/generated/types.gen.ts, src/api/openapi.json, src/hooks/useAlertsData.ts, src/hooks/usePromptsData.ts, src/hooks/useWorkspacesData.ts
Depends on https://github.com/stacklok/codegate/pull/634
=> fix: breaking changes in openapi spec

src/features/workspace-system-prompt/components/__tests__/system-prompt-editor.test.tsx, src/routes/__tests__/route-workspace.test.tsx
Adds test for the system prompt editor & workspace route.
The tests aren't very thorough, and rely heavily on mocking, but give *some* safety.
=> test: system prompt editor & workspace route

src/components/react-query-provider.tsx, src/features/workspace/components/workspaces-selection.tsx, src/features/workspace/hooks/use-activate-workspace.ts, src/features/workspace/hooks/use-active-workspaces.ts, src/features/workspace/hooks/use-list-workspaces.ts, src/hooks/useWorkspacesData.ts, src/main.tsx, src/mocks/msw/handlers.ts, src/routes/route-workspaces.tsx
- adds a "mutation" hook to the workspace selection component, which allows toggling workspaces
- wraps the app a custom react-query QueryClientProvider, which subscribes to events in the query cache to enable the following
- when the cached value for GET /api/v1/workspaces/active is updated, the provider will compare the active workspace ID — if it is new, it will invalidate the query cache and post a toast notification with the newly activated workspace name
- a `useActiveWorkspaces` hook is implemented, which polls the server on an interval, as well as every time the window is focused, or it reconnects — this should ensure that it is always up to date
https://github.com/user-attachments/assets/2965faac-1f4a-4477-a3d0-c9585f131e91
Closes #126
Closes #124
=> feat: enable toggle workspace, invalidate on workspace update

src/features/workspace-system-prompt/components/system-prompt-editor.tsx, src/features/workspace/components/workspace-name.tsx
- adds a missing href to leave the "workspace settings" page
- adds `shrink-0` to cards on "workspace settings" page to prevent them from clipping their contents
=> fix: workspace ui nits

src/api/generated/@tanstack/react-query.gen.ts, src/api/generated/sdk.gen.ts, src/api/generated/types.gen.ts, src/api/openapi.json, src/components/react-query-provider.tsx, src/features/workspace/components/workspaces-selection.tsx, src/features/workspace/hooks/use-active-workspace-name.ts, src/features/workspace/hooks/use-active-workspaces.ts, src/hooks/useAlertsData.ts, src/hooks/usePromptsData.ts, src/mocks/msw/handlers.ts, src/routes/__tests__/route-dashboard.test.tsx
Integrates the new `/workspace/:name/*` endpoints for querying alerts & prompts.
=> feat: workspace scoped queries (messages & alerts)

src/App.tsx, src/main.tsx
this fixes providers so that:
- ui-kit is properly connected with react-router
- errors related to ui-kit are no longer swallowed in such a way that they appear like react-query related errors
=> fix: fix providers for better debugging

src/features/workspace/components/__tests__/workspace-creation.test.tsx, src/features/workspace/components/workspace-creation.tsx
Just fixes a small UI nit — now you can use {enter} to submit the workspace creation form.
=> fix: enter to submit workspace create form

icons/FlipBackward.svg, src/api/generated/@tanstack/react-query.gen.ts, src/api/generated/sdk.gen.ts, src/api/generated/types.gen.ts, src/api/openapi.json, src/components/icons/FlipBackward.tsx, src/components/icons/index.ts, src/features/workspace/hooks/use-archived-workspaces.ts, src/features/workspace/hooks/use-restore-workspace.ts, src/mocks/msw/handlers.ts, src/routes/__tests__/route-workspaces.test.tsx, src/routes/route-workspaces.tsx
https://github.com/user-attachments/assets/b21a584a-950e-4d8a-a75d-5925f6c77fc8
=> feat: show archived workspaces and restore it

src/features/workspace-system-prompt/components/__tests__/system-prompt-editor.test.tsx, src/features/workspace-system-prompt/components/system-prompt-editor.tsx, src/features/workspace/components/archive-workspace.tsx
- makes the "archive" button "destructive"
- removes the "cancel" button from update system prompt
- renames the "save" button for update system prompt
=> fix: buttons in workspace page

src/features/workspace/components/workspace-creation.tsx, src/features/workspace/components/workspace-name.tsx, src/features/workspace/hooks/use-create-workspace.ts, src/routes/__tests__/route-workspace.test.tsx
https://github.com/user-attachments/assets/adf178d8-2e5c-4e8d-a6d3-96c0f59a89a7
=> feat: rename workspace

package-lock.json, package.json, src/components/Header.tsx, src/components/HoverPopover.tsx, src/features/dashboard-codegate-status/components/codegate-status-polling-control.tsx
Implements the new UIKit `OptionsSchema` type for Menu & ListBox components. See the relevant PR here: https://github.com/stacklok/frontend/pull/1077
=> refactor: implement new UIKit options schema

src/components/PromptList.tsx, src/components/__tests__/PromptList.test.tsx, src/lib/utils.ts, src/routes/route-chat.tsx
Following some issues with copilot, I tried to checked some specific use cases:
- tagged file
- highlighted snippet
- fallback text
=> fix: parsing promptList text and breadcrumb

src/hooks/use-kbd-shortcuts.ts, src/lib/hrefs.ts, src/routes/route-workspaces.tsx
Following the adage of "build the things you want to see in the product"  — I added a hook that can be used to wire up keyboard shortcuts.
While working on "hard delete" for workspaces, I found myself wanting "C" to create a **lot**. I think overtime we can instrument the entire app for productivity like this.
=> feat: useKbdShortcuts hook & example implementation

src/components/AlertsTable.tsx, src/hooks/useAlertsData.ts
**AFTER**
"1463" alt="Screenshot 2025-01-24 at 12 24 53" src="https://github.com/user-attachments/assets/d983131c-29be-438d-ba25-b706422e397f" />
**BEFORE**
=> fix: sort filtered alerts before pagination

eslint.config.js, src/hooks/use-toast-mutation.ts
Uses the `no-restricted-imports` rule to disallow using `useMutation` from `@tanstack/react-query` and standardises use of the `useToastMutation` wrapper (better UX)
Closes #182
=> chore: enforce use of useToastMutation

src/features/workspace/components/__tests__/archive-workspace.test.tsx, src/features/workspace/components/__tests__/workspace-name.test.tsx, src/features/workspace/components/archive-workspace.tsx, src/features/workspace/components/workspace-custom-instructions.tsx, src/features/workspace/hooks/use-archive-workspace-button.tsx, src/features/workspace/hooks/use-confirm-hard-delete-workspace.tsx
=> fix: workspace hard delete nits

src/features/workspace/components/workspace-name.tsx, src/features/workspace/components/workspaces-selection.tsx
Small UI tweak to add a link to each workspace's settings page in the workspace selector.
I also tidied up a few spacing/color inconsistencies in the workspace selector.
https://github.com/user-attachments/assets/c52ffc61-2a99-4946-85cf-b4e26cc27e6e
=> feat: quick "go to settings" for workspace selector

src/api/generated/@tanstack/react-query.gen.ts, src/api/generated/sdk.gen.ts, src/api/generated/types.gen.ts, src/api/openapi.json, src/features/alerts/components/__tests__/table-alerts.test.tsx, src/features/alerts/components/table-alert-token-usage.tsx, src/features/alerts/components/table-alerts.tsx, src/features/alerts/lib/get-alert-token-usage.ts, src/features/alerts/mocks/alert-malicious.mock.ts, src/features/alerts/mocks/alert-secret.mock.ts, src/lib/__tests__/currency.test.ts, src/lib/currency.ts, src/routes/__tests__/route-dashboard.test.tsx, src/routes/route-dashboard.tsx
* Shows token usage on an alert conversation as a cell in the alerts table
* Tidies up some code relating to the alerts table (mainly location within the codebase)
* Depends on https://github.com/stacklok/codegate/pull/788
https://github.com/user-attachments/assets/9aeca2fe-77df-49bf-af1b-234ab931ad4a
=> feat: show token usage on alerts table

package-lock.json, package.json, src/components/CopyToClipboard.tsx, src/components/Error.tsx, src/components/HoverPopover.tsx, src/components/ui/sheet.tsx, src/components/ui/sidebar.tsx, src/features/alerts/components/__tests__/table-alerts.test.tsx, src/features/alerts/components/table-alert-token-usage.tsx, src/features/alerts/components/table-alerts.tsx, src/features/header/components/header-status-menu.tsx, src/features/header/constants/certificate-menu-items.tsx, src/features/header/constants/help-menu-items.tsx, src/features/workspace/components/table-actions-workspaces.tsx, src/features/workspace/components/workspace-custom-instructions.tsx, src/features/workspace/components/workspaces-selection.tsx, src/routes/route-workspaces.tsx
this pr replaced lucide icons with untitled, the same icon library that is used in ui-kit and all our other projects
most icons had a direct equivalent, except the robot icon used for the built in prompts. I just swapped that for a chat bubble instead 
for the updates, when there was no "shield alert" icon when an update is available, so I replaced it with a hexagon alert icon instead.
=> feat: replace lucide icons with untitled icons

package-lock.json
#221 appears to have deleted and re-created the lockfile. After rebasing from main, I wasn't able to start the dev server on MacOS — this PR just restores the lockfile to it's previous state, with the `lucide` dependency removed, and the `@untitled-ui/icons-react` added.
=> fix: restore lockfile

src/features/alerts/hooks/use-query-get-workspace-alerts-malicious-pkg.ts, src/features/alerts/hooks/use-query-get-workspace-alerts-secrets.ts, src/features/workspace/hooks/use-active-workspace-name.ts, src/hooks/useAlertsData.ts, src/hooks/usePromptsData.ts
* While working on #230 I noticed that we weren't following some [best-practices](https://tanstack.com/query/latest/docs/framework/react/guides/render-optimizations#memoization) around use of the `select` parameter for react-query's `useQuery` hook:
>The select function will only re-run if:
> - the select function itself changed referentially
> - data changed
> This means that an inlined select function, as shown above, will run on every render. To avoid this, you can wrap the select function in useCallback, or extract it to a stable function reference if it doesn't have any dependencies
* This fixes any usage errors throughout the codebase (mainly created by me :D) and documents them, to attempt to avoid any regressions.
=> fix(alerts): memoize selecting alerts

src/features/alerts/components/__tests__/alerts-summary-workspace-token-usage.test.tsx, src/features/alerts/components/__tests__/table-alerts.test.tsx, src/features/alerts/components/alerts-summary.tsx, src/features/alerts/components/table-alert-token-usage.tsx, src/features/alerts/components/token-usage-by-providers.tsx, src/lib/format-number.ts
Uses compact notation when displaying token usage, so the numbers don't become hard to parse/work with in the UI.
=> feat: format token usage with "compact" notation

src/components/react-query-provider.tsx, src/lib/react-query-utils.ts
- adds a helper for setting cache lifetime of data fetched with react-query 
- applies it globally as `defaultSettings` to all queries (can be overridden each time we call `useQuery`)
- fixes #250 
- workaround for https://github.com/stacklok/codegate/issues/936
=> fix: implement default caching options for react-query

src/components/AlertDetail.tsx, src/routes/route-chat.tsx
I retrieved the old logic for showing secrets and malicious pkg alerts, showing it into the conversation page.
We have a lot of dogecoin secret false positive, that we need to solve on BE ( issue created [here](https://github.com/stacklok/codegate/issues/985))
We are going to fine tune this section, but I guess for now it would be better to show this kind of detail rather than hide them.
=> feat: show alert detail in the conversation page

src/components/empty-state.tsx, src/features/dashboard-messages/components/__tests__/table-messages.empty-state.test.tsx, src/features/dashboard-messages/components/table-messages-empty-state.tsx, src/features/dashboard-messages/components/table-messages.tsx, src/features/header/components/header-active-workspace-selector.tsx
=> fix: error displayed when activating workspace

src/features/workspace/components/__tests__/workspace-name.test.tsx, src/features/workspace/components/__tests__/workspace-preferred-model.test.tsx, src/features/workspace/components/workspace-custom-instructions.tsx, src/features/workspace/components/workspace-name.tsx, src/features/workspace/components/workspace-preferred-model.tsx, src/features/workspace/hooks/use-preferred-preferred-model.ts, src/hooks/useFormState.ts
https://github.com/user-attachments/assets/a82da24c-86c7-4167-9a32-692eec178a0d
=> feat: make preferred model form consistent with the other forms

src/features/workspace/components/workspace-custom-instructions.tsx
I think enabling word wrap is a better default, because I found that it's annoying otherwise.
=> feat: enable word wrap for prompt editor

src/markdown/certificates/linux-install.md, src/markdown/certificates/linux-remove.md, src/markdown/certificates/macos-install.md, src/markdown/certificates/macos-remove.md, src/markdown/certificates/windows-install.md, src/markdown/certificates/windows-remove.md, src/routes/__tests__/route-certificates.test.tsx
- Use docs style to use bold for UI elements now that we have
markdown support
- Tighten up the CLI line breaks a bit
- Minor wording updates
=> docs: small updates for the cert instructions

src/features/workspace/components/workspace-activate-button.tsx, src/routes/__tests__/route-workspace.test.tsx, src/routes/route-workspace.tsx
https://github.com/user-attachments/assets/4917c98c-58ed-4ddf-a393-2924e65680a0
=> feat: add activate workspace button into detail page

src/api/generated/@tanstack/react-query.gen.ts, src/api/generated/sdk.gen.ts, src/api/generated/types.gen.ts, src/api/openapi.json, src/features/providers/components/table-providers.tsx, src/features/providers/components/workspaces-by-provider.tsx, src/features/providers/hooks/use-confirm-delete-provider.tsx, src/features/providers/hooks/use-invalidate-providers-queries.ts, src/features/providers/hooks/use-query-workspaces-by-provider.ts, src/features/workspace/hooks/use-invalidate-workspace-queries.ts
Show the list of workspaces impacted by provider deletion, in this way the user can have a bit of context.
I thought that the badge can work, but I would fine tune later with James.
nit: We already that the table will be replaced, we are going to show the workspaces list and the models, and James is thinking on a different component. For that reason I would avoid to add test right now.
=> feat: add workspaces impacted by provider deletion

package-lock.json, package.json, src/api/generated/types.gen.ts, src/api/openapi.json, src/features/providers/components/workspaces-by-provider.tsx, src/features/workspace/components/__tests__/workspace-muxing-model.test.tsx, src/features/workspace/components/workspace-models-dropdown.tsx, src/features/workspace/components/workspace-muxing-model.tsx, src/features/workspace/hooks/use-muxing-rules-form-workspace.ts, src/features/workspace/lib/utils.ts
Add `matcher_type` select for supporting muxing fim and chat.
https://github.com/user-attachments/assets/61b0c45e-7cf2-4315-916a-6234ec7d4a26
=> feat: support muxing fim and chat

src/api/generated/@tanstack/react-query.gen.ts, src/api/generated/sdk.gen.ts, src/api/generated/types.gen.ts, src/api/openapi.json, src/features/workspace/components/__tests__/workspace-name.test.tsx, src/features/workspace/components/workspace-name.tsx, src/features/workspace/hooks/use-mutation-update-workspace.ts, src/mocks/msw/handlers.ts
Companion PR for https://github.com/stacklok/codegate/pull/1107
=> fix: handle breaking changes to workspace config

index.html, src/global.d.ts, src/hooks/useSse.ts, src/lib/__tests__/utils.test.ts, src/lib/utils.ts, src/main.tsx, tsconfig.app.json
In order to allow users to override the `BASE_API_URL` rather than using localhost, I switch the entry point for reading the env var to index.html, in this way it is much cleaner to override in the codegate `entrypoint.sh`.
This use case was raised up from a user in discord and it is actually handled by `sed` within the entrypoint.
No breaking changes
**Replace BASE_API_URL at `docker run...`**
Setting the env at docker run time we are going to replace the `${BASE_API_URL}` value in the html
https://github.com/user-attachments/assets/5d2cecb7-ad5b-4f9e-b1e2-40739ca0c565
**Default use case, no env replacement**
In case the `BASE_API_URL` is not replaced at docker run time, it will use the `VITE_BASE_API_URL` default value
https://github.com/user-attachments/assets/da4b081b-5780-4d0f-9b19-7e …
=> chore: get base api url from index.html

index.html, src/global.d.ts, src/hooks/useSse.ts, src/lib/__tests__/utils.test.ts, src/lib/utils.ts, src/main.tsx, src/vite-env.d.ts
Refactor env from `BASE_API_URL` to `DASHBOARD_API_BASE_URL`
=> refactor: dashboard api base url env

package-lock.json, package.json
```shell
┌────────────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────────────┬─────────────────────────────────────────────────────────────┐
│    Library     │ Vulnerability  │ Severity │ Status │ Installed Version │      Fixed Version      │                            Title                            │
├────────────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────────────┼─────────────────────────────────────────────────────────────┤
│ @babel/runtime │ CVE-2025-27789 │ MEDIUM   │ fixed  │ 7.26.0            │ 7.26.10, 8.0.0-alpha.17 │ Babel is a compiler for writing next generation JavaScript. │
│                │                │          │        │                   │                         │ When using ...... …
```
=> fix: use package.json overrides to bump `@babel/runtime` & `prismjs` to fix npm audit warnings
